<technologies>
<?php foreach ($this->technologies as $technology): ?>
	<technology>
		<name><![CDATA[<?= $technology->name; ?>]]></name>
		<version><?= $technology->version ? '<![CDATA['.$technology->version.']]>' : '' ?></version>
		<releasedate><?= !preg_match("/0000-00-00/", $technology->release_date) ? $technology->release_date : '' ?></releasedate>
		<description><?= $technology->description ? '<![CDATA['.$technology->description.']]>' : '' ?></description>
		<iprights><?= $technology->iprights ? '<![CDATA['.$technology->iprights.']]>' : '' ?></iprights>
		<license><?= $technology->license; ?></license>
		<dateadded><?= $technology->date_added; ?></dateadded>
	</technology>
<?php endforeach; ?>
</technnologies>
