<p>Welcome to the site administration area. From here you can;</p>
<ul>
	<li>
		<a href="/admin/status">Check System Health</a><br/>
		In this area you can check the status of the system, including checking the error logs
		and the status of the search indexer.
	</li>
	<li>
		<a href="/admin/technology">Manage Technologies</a><br/>
		Remove any technologies from the survey site.
	</li>
	<li>
		<a href="#">Manage Revisions</a><br/>
		Remove any revisions from the survey site.
	</li>
	<li>
		<a href="/admin/user">Manage Users</a><br/>
		Remove any users from the survey site. You can also grant admin priviledges and issue
		password resets from here.
	</li>
</ul>