<div>
  <h2>PHP Environment</h2>
  <table>
    <tr><td style="font-weight: bold;">Relation</td><td><?php echo php_sapi_name(); ?></td></tr>
    <tr><td style="font-weight: bold;">Version</td><td><?php echo phpversion(); ?></td></tr>
    <tr><td style="font-weight: bold;">OS</td><td><?php echo PHP_OS; ?></td></tr>
    <?php if (strtoupper(substr(PHP_OS, 0, 3)) !== "WIN"): ?>
    <?php $dat = getrusage(); ?>
    <tr><td style="font-weight: bold;">Pagefaults</td><td><?php echo $dat["ru_majflt"]; ?></td></tr>
    <tr><td style="font-weight: bold;">Swaps</td><td><?php echo $dat["ru_nswap"]; ?></td></tr>
    <tr><td style="font-weight: bold;">User Time (ms)</td><td><?php echo $dat["ru_utime.tv_usec"]; ?></td></tr>
    <tr><td style="font-weight: bold;">User Time (s)</td><td><?php echo $dat["ru_utime.tv_sec"]; ?></td></tr>
    <?php endif; ?>
  </table>
  <h2>Search Module</h2>
  <p>
    Indexer Status:&nbsp;
  <?php if (file_exists(APPLICATION_PATH."/../var/processes/indexer")): ?>
    <span style="color: green;">Running</span>&nbsp;<a href="/admin/process/stop/ps/indexer">Stop Indexer</a>
  <?php else: ?>
    <span style="color: red;">Stopped</span>&nbsp;<a href="/admin/process/start/ps/indexer">Start Indexer</a>
  <?php endif; ?>
    &nbsp;<a href="/admin/process/log/ps/indexer">Read Log</a>
  </p>
  <h2>Twitter Module</h2>
  <table>
    <tr><th>Remaining API calls this hour</th><td><?php echo $this->remainingTwitterApiCalls; ?></td></tr>
  </table>
  <input type="button" onclick="javascript: window.location='/admin/twitter/clearstatus';" value="Flush Message Cache"/>
</div>