<div>
  <h2>PHP Environment</h2>
  <table>
    <tr><td style="font-weight: bold;">Zend Framework</td><td><?php echo Zend_Version::VERSION; ?></td></tr>
    <tr><td style="font-weight: bold;">Relation</td><td><?php echo php_sapi_name(); ?></td></tr>
    <tr><td style="font-weight: bold;">Version</td><td><?php echo phpversion(); ?></td></tr>
    <tr><td style="font-weight: bold;">OS</td><td><?php echo PHP_OS; ?></td></tr>
    <?php if (strtoupper(substr(PHP_OS, 0, 3)) !== "WIN"): ?>
    <?php $dat = getrusage(); ?>
    <tr><td style="font-weight: bold;">Pagefaults</td><td><?php echo $dat["ru_majflt"]; ?></td></tr>
    <tr><td style="font-weight: bold;">Swaps</td><td><?php echo $dat["ru_nswap"]; ?></td></tr>
    <tr><td style="font-weight: bold;">User Time (ms)</td><td><?php echo $dat["ru_utime.tv_usec"]; ?></td></tr>
    <tr><td style="font-weight: bold;">User Time (s)</td><td><?php echo $dat["ru_utime.tv_sec"]; ?></td></tr>
    <?php endif; ?>
  </table>
  <h2>Process Module</h2>
  <?php if (sizeof($this->processes)): ?>
    <table>
      <tr><th>Process Name</th><th>Status</th><th></th></tr>
      <?php foreach ($this->processes as $process): ?>
      <tr>
        <td><?php print $process->getName(); ?></td>
        <td>
        <?php if ($process->isRunning()): ?>
          <span style="color: green;">Running</span>
        <?php else: ?>
          <span style="color: red;">Stopped</span>
        <?php endif; ?>
        </td>
        <td>
        <?php if ($process->isRunning()): ?>
          <a href="/admin/process/stop/ps/<?php echo $process->getName(); ?>">Stop</a>
        <?php else: ?>
          <a href="/admin/process/start/ps/<?php echo $process->getName(); ?>">Start</a>
        <?php endif; ?>
        </td>
      </tr>
      <?php endforeach; ?>
    </table>
  <?php else: ?>
    <p>There are currently not any processes installed.</p>
  <?php endif; ?>
  </p>
  <h2>Twitter Module</h2>
  <table>
    <tr><th>Remaining API calls this hour</th><td><?php echo $this->remainingTwitterApiCalls; ?></td></tr>
  </table>
  <input type="button" onclick="javascript: window.location='/admin/twitter/clearstatus';" value="Flush Message Cache"/>
</div>