<?= $this->doctype(); ?>
<html xmlns="http://www.w3c.org/1999/xhtml">
<head>
	<?= $this->headTitle(($this->title ? "{$this->title} :: " : "").'SemTech Survey'); ?>
	<?= $this->headLink(array('rel' => 'icon', 'href' => '/images/favicon.png', 'type' => 'image/png'))->appendStylesheet('/stylesheets/minimal.css', 'screen'); ?>
	<?= $this->headScript()->appendFile("/js/jquery.js"); ?>
</head>
<body>
	<div class="content">
		<h2><?= $this->title; ?></h2>
		<p><a href="javascript: window.close();">Close This Window</a></p>
		<?= $this->layout()->content; ?>
	</div>
	<script type="text/javascript">
	//<![CDATA[
  var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
  document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
  //]]>
  </script>
  <script type="text/javascript">
  //<![CDATA[
  try {
  var pageTracker = _gat._getTracker("UA-9948976-1");
  pageTracker._trackPageview();
  } catch(err) {}
  //]]>
  </script>
</body>
</head>