<?= $this->doctype(); ?>
<html xmlns="http://www.w3c.org/1999/xhtml">
<head>
	<?= $this->headTitle(($this->title ? "{$this->title} :: " : "").'SemTech Survey'); ?>
	<?= $this->headLink(array('rel' => 'icon', 'href' => '/images/favicon.png', 'type' => 'image/png'))->appendStylesheet('/stylesheets/minimal.css', 'screen'); ?>
	<?= $this->headScript()->appendFile("/js/jquery.js"); ?>
</head>
<body>
	<div class="content">
		<h2><?= $this->title; ?></h2>
		<p><a href="javascript: window.close();">Close This Window</a></p>
		<?= $this->layout()->content; ?>
	</div>
</body>
</head>