#!/usr/bin/env php
<?php
defined('APPLICATION_PATH') || define('APPLICATION_PATH', realpath(dirname(__FILE__) . '/../application'));
defined('APPLICATION_ENV') || define('APPLICATION_ENV', 'development');
set_include_path(implode(PATH_SEPARATOR, array(
  get_include_path(),
  realpath(APPLICATION_PATH."/../library")
)));

require_once("Zend/Application.php");
$application = new Zend_Application(
  APPLICATION_ENV,
  APPLICATION_PATH.'/config/cliapplication.ini'
);
$application->bootstrap();

$log = Zend_Registry::get("log");
$log->addWriter(new Zend_Log_Writer_Stream(APPLICATION_PATH.'/../var/logs/indexer.log'));

$log->info("Semtech Survey Indexer started");

$log->info("Attempting to load indexer.ini...");

$settings = array();
try
{
  $settings = new Zend_Config_Ini(APPLICATION_PATH."/config/indexer.ini");
}
catch (Zend_Config_Exception $e)
{
  $log->info("Unable to find ".APPLICATION_PATH."/config/indexer.ini, assuming defaults.");
  $settings->searchindex = APPLICATION_PATH."/../var/search";
}

try
{
  $searchindex = Zend_Search_Lucene::open($settings["searchindex"]);
}
catch (Zend_Search_Lucene_Exception $e)
{
  $log->info("Search index does not exist yet... creating a new one.");
  try
  {
    $searchindex = Zend_Search_Lucene::create($settings["searchindex"]);
  }
  catch (Zend_Search_Lucene_Exception $e)
  {
    $log->err("Failed to load a search index in ".$settings["searchindex"]);
  }
}

$technologiestable = new Semtech_Model_DbTable_Technologies();
foreach ($technologiestable->fetchAll() as $technology)
{
  if (!technology_indexed($technology, $searchindex))
  {
    $doc = new Zend_Search_Lucene_Document();
    $doc->addField(Zend_Search_Lucene_Field::Text('name', $technology->name));
    $doc->addField(Zend_Search_Lucene_Field::UnStored('description', $technology->description));
    $doc->addField(Zend_Search_Lucene_Field::Keyword('url', $technology->url));
    $doc->addField(Zend_Search_Lucene_Field::Keyword('technologyid', $technology->id));

    $searchindex->addDocument($doc);

    $log->info("Added {$technology->name} to the search index.");
  }
}

$log->info("Optimizing search index...");
$searchindex->optimize();
$log->info("Done.");

$searchindex->commit();

$log->info("Indexing complete. Exiting...");

exit(0);

function technology_indexed($technology, $searchindex)
{
  $hits = $searchindex->termDocs(new Zend_Search_Lucene_Index_Term($technology->id, 'technologyid'));
  $matched = false;
  if (count($hits))
  {
    $matched = true;
  }
  
  return $matched;
}

