#!/usr/bin/env php
<?php
define('APP_ROOT', realpath(dirname(dirname(__FILE__))));

set_include_path(APP_ROOT.'/library'.PATH_SEPARATOR.get_include_path());

require_once('Zend/Loader.php');
Zend_Loader::registerAutoload();

try {
	$opts = new Zend_Console_Getopt("search_term");
	$opts->parse();
	$args = $opts->getRemainingArgs();
} catch (Zend_Console_Getopt_Exception $e) {
	echo $e->getUsageMessage();
	exit;
}

$searchterm = $args[0];
$index = Zend_Search_Lucene::open(APP_ROOT.'/var/index');
$query = Zend_Search_Lucene_Search_QueryParser::parse($searchterm);
$hits = $index->find($query);
foreach ($hits as $hit)
{
	echo $hit->name." {$hit->url} ({$hit->technologyid})\n";
} 
?>
