<a href="<?= $this->url(array("techid" => $this->technology->id), "technology"); ?>">Back to main entry</a>
<?php if (Zend_Auth::getInstance()->hasIdentity()): ?>
<?= $this->form; ?>
<?php endif; ?>
<?php foreach ($this->technology->getComments() as $comment): ?>
<div>
	<p>Posted by: <?= $comment->getPoster()->name; ?> (<?= date("jS F Y", strtotime($comment->postedon)); ?>)</p>
	<p><?= $comment->comment; ?></p>
</div>
<?php endforeach; ?>