<a href="<?= $this->url(array("techid" => $this->technology->id), "technology"); ?>">Back to main entry</a>

<div class="relationtools">
	<p><a href="/relation/reference/techid/<?= $this->technology->id; ?>">Add Reference</a> | <a href="/relation/relation/techid/<?= $this->technology->id; ?>">Add Relation</a></p>
</div>

<div style="float: right; width: 350px;">
	<h2>Related Technologies</h2>
	<?= $this->partial("partials/relatedtechs.phtml", array('relations' => $this->technology->getRelations())); ?>
</div>

<div style="float: left; width: 350px;">
	<h2>References</h2>
	<?= $this->partial("partials/references.phtml", array('references' => $this->technology->getReferences())); ?>
</div>